import os
import json
from langchain.tools import BaseTool
from langchain_community.tools import DuckDuckGoSearchRun
from ddgs import DDGS
import yfinance as yf
import pandas_ta as ta
import pandas as pd
from typing import Optional

"""
This file contains the tools for the stock market analysis agent.
"""

class StockDataTool(BaseTool):
    """Fetches historical stock data for a given ticker."""
    name: str = "Stock_Data_Fetcher"
    description: str = (
        "Fetches historical stock data for a given ticker. "
        "Input should be a stock ticker symbol (e.g., 'AAPL')."
    )

    def _run(self, ticker: str) -> pd.DataFrame:
        """Fetches the stock data."""
        stock = yf.Ticker(ticker)
        # Get historical market data
        hist = stock.history(period="1y")
        if hist.empty:
            return f"Error: Could not find data for ticker {ticker}."
        return hist.to_string()

class TechnicalIndicatorTool(BaseTool):
    """Calculates technical indicators for a given stock."""
    name: str = "Technical_Indicator_Calculator"
    description: str = (
        "Calculates various technical indicators for a stock. "
        "Input should be a stock ticker symbol (e.g., 'AAPL')."
    )

    def _run(self, ticker: str) -> str:
        """Calculates the technical indicators."""
        stock = yf.Ticker(ticker)
        hist = stock.history(period="1y")
        if hist.empty:
            return f"Error: Could not find data for ticker {ticker}."
        
        # Calculate indicators
        hist.ta.rsi(append=True)
        hist.ta.macd(append=True)
        hist.ta.sma(length=20, append=True)
        hist.ta.bbands(append=True)
        
        # Return the last few rows with indicators
        return hist.iloc[-5:].to_string()

class EconomicResearcherTool(BaseTool):
    """Performs internet searches for financial news and sentiment."""
    name: str = "Economic_Researcher"
    description: str = (
        "Performs internet searches for financial news, sentiment, and "
        "macroeconomic factors about a provided company. "
        "Input should be a targeted search query (e.g., 'Apple Inc. investor sentiment last 6 months'). "
        "**Crucially, you must focus on trusted sources published within the last 6-12 months.** Avoid wikis, forums, or blogs."
    )
    
    def _run(self, query: str) -> str:
        """Executes an internet search and returns a formatted string of results."""
        try:
            with DDGS() as ddgs:
                # Fetch the top 5 results for the query
                results = list(ddgs.text(query, max_results=5))
                if not results:
                    return "No results found."
                
                # Format the results into a single string
                formatted_results = []
                for i, result in enumerate(results):
                    formatted_results.append(
                        f"Result {i+1}:\n"
                        f"  Title: {result.get('title', 'N/A')}\n"
                        f"  Snippet: {result.get('body', 'N/A')}\n"
                        f"  URL: {result.get('href', 'N/A')}\n"
                    )
                return "\n".join(formatted_results)
        except Exception as e:
            return f"An error occurred during the search: {e}"

class FinancialReportFormatter(BaseTool):
    """Formats data into a professional financial report."""
    name: str = "Financial_Report_Formatter"
    description: str = (
        "Formats a collection of data into a professional financial report written in Markdown. "
        "Input should be a string containing all the information to be included in the report. "
        "Ensure the output is clean, well-structured, and avoids using characters that could be misinterpreted by renderers (e.g., escape dollar signs like `\\$`)."
    )

    def _run(self, data: str) -> str:
        """Formats the data into a report."""
        report = f"""
# Financial Report

## Analysis Summary
{data}

## Disclaimer
This report is generated by an AI and is for informational purposes only. It is not financial advice.
        """
        return report

class FinancialReportEditor(BaseTool):
    """Formats data into a professional financial report."""
    name: str = "Financial_Report_Editor"
    description: str = (
        "Lead editor for the Financial Times, editing the financial report to be consistent and have a sense of direction and thorough belief in where the stock is heading in the future "
        "Input should be a string containing all the information to be included in the report."
    )

    def _run(self, data: str) -> str:
        """Formats the data into a report."""
        report = f"""

{data}

## Disclaimer
This report is generated by an AI and is for informational purposes only. It is not financial advice.
        """
        return report

class MemoryTool(BaseTool):
    """A tool to save and retrieve past financial reports."""
    name: str = "Memory_Tool"
    description: str = (
        "Used to save and retrieve past financial reports to provide long-term context. "
        "Use 'save' to store a new report and 'retrieve' to fetch past reports for a ticker."
    )
    _file_path: str = "report_memory.json"

    def _load_memory(self) -> dict:
        """Loads the memory from a local JSON file."""
        if not os.path.exists(self._file_path):
            return {}
        with open(self._file_path, "r") as f:
            return json.load(f)

    def _save_memory(self, memory: dict):
        """Saves the memory to a local JSON file."""
        with open(self._file_path, "w") as f:
            json.dump(memory, f, indent=2)

    def _run(self, action: str, ticker: Optional[str] = None, report: Optional[str] = None) -> str:
        """
        Saves or retrieves a report.
        - To save: action='save', ticker='TICKER', report='...'
        - To retrieve: action='retrieve', ticker='TICKER'
        """
        memory = self._load_memory()
        
        if action == "save":
            if not ticker or not report:
                return "Error: 'save' action requires a 'ticker' and a 'report'."
            if ticker not in memory:
                memory[ticker] = []
            memory[ticker].append(report)
            self._save_memory(memory)
            return f"Report for {ticker} saved successfully."
            
        elif action == "retrieve":
            if not ticker:
                return "Error: 'retrieve' action requires a 'ticker'."
            if ticker in memory and memory[ticker]:
                return "\n---\n".join(memory[ticker])
            return f"No past reports found for {ticker}."
            
        return "Error: Invalid action. Use 'save' or 'retrieve'."
